export default {
  SEARCH_CATEGORY: 'SEARCH_CATEGORY',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
  LOAD_CATEGORY: 'LOAD_CATEGORY',
  LOAD_PRODUCT: 'LOAD_PRODUCT',
  LOAD_PRODUCT_EXTENDED: 'LOAD_PRODUCT_EXTENDED',
  LOAD_PRODUCT_IMAGES: 'LOAD_PRODUCT_IMAGES',
  LOAD_OPTION: 'LOAD_OPTION',
  LOAD_QUANTITY: 'LOAD_QUANTITY',
  LOAD_DATE: 'LOAD_DATE',
  SELECT_CATEGORY: 'SELECT_CATEGORY',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  SELECT_OPTION: 'SELECT_OPTION',
  SELECT_QUANTITY: 'SELECT_QUANTITY',
  SELECT_DATE: 'SELECT_DATE',
  GET_ITEMS: 'GET_ITEMS'
}