export default {
    LOAD_CATEGORY: 'LOAD_CATEGORY',
    LOAD_PRODUCT: 'LOAD_PRODUCT',
    LOAD_OPTION: 'LOAD_OPTION',
    LOAD_QUANTITY: 'LOAD_QUANTITY',
    LOAD_DATE: 'LOAD_DATE',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    SELECT_OPTION: 'SELECT_OPTION',
    SELECT_QUANTITY: 'SELECT_QUANTITY',
    SELECT_DATE: 'SELECT_DATE',
    GET_ITEMS: 'GET_ITEMS'
}