let BASE_URL = QC_BASE_URI

export default {
    BASE_URL: BASE_URL,
    CUSTOMER_URL: BASE_URL + 'account/customer',
    CREATE_CUSTOMER: 'CREATE_CUSTOMER',
    GET_CUSTOMER: 'GET_CUSTOMER',
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    SET_CUSTOMER: 'SET_CUSTOMER',
    CLEAR_CUSTOMER: 'CLEAR_CUSTOMER',
    SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
    UPDATE_BILLING_ADDRESS: 'UPDATE_BILLING_ADDRESS',
    SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
    UPDATE_SHIPPING_ADDRESS: 'UPDATE_SHIPPING_ADDRESS'
}