export default {
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    GET_PRODUCT: 'GET_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    SET_PRODUCT: 'SET_PRODUCT',
    SET_PRODUCTS: 'SET_PRODUCTS'
}