let BASE_URL = QC_BASE_URI

export default {
    BASE_URL: BASE_URL,
    CART_URL: BASE_URL + 'checkout/cart',
    CHECKOUT_URL: BASE_URL + 'checkout/checkout',
    SET_CUSTOMER: 'SET_CUSTOMER',
    SET_ORDER: 'SET_ORDER',
    SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
    SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
    SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
    SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD',
    SET_PAYMENT_TYPE: 'SET_PAYMENT_TYPE',
    SET_SHIPPING_METHOD: 'SET_SHIPPING_METHOD'
}