export default {
    CUSTOMER_ID: 'customer_id',
    USER_NAME: 'user_name',
    DISPLAY_NAME: 'display_name',
    PREFERRED_NAME: 'preferred_name',
    FIRST_NAME: 'first_name',
    MIDDLE_NAME: 'middle_name',
    LAST_NAME: 'last_name',
    INITIAL: 'initial',
    TITLE: 'title',
    SALUTATION: 'title',
    SUFFIX: 'suffix',
    GENDER: 'gender',
    MARITAL: 'marital',
    DOB_YEAR: 'dob_year',
    DOB_MONTH: 'dob_month',
    DOB_DAY: 'dob_day',
    DOB: 'dob',
    SIN: 'sin',
    COMPANY_NAME: 'company_name',
    EMAIL: 'email',
    MOBILE: 'mobile',
    TELEPHONE: 'telephone',
    PASSWORD: 'password',
    CONFIRM: 'confirm'
}