let BASE_URL = QC_BASE_URI

export default {
  BASE_URL: BASE_URL,
  CUSTOMER_URL: BASE_URL + 'account/customer',
  SET_CUSTOMERS: 'SET_CUSTOMERS',
  SET_CUSTOMER_SUMMARY: 'SET_CUSTOMER_SUMMARY',
  SET_CUSTOMER_EXTENDED: 'SET_CUSTOMER_EXTENDED',
  SET_CUSTOMER_HISTORY: 'SET_CUSTOMER_HISTORY',
  SET_CUSTOMER_PROFILE_IMAGE: 'SET_CUSTOMER_PROFILE_IMAGE',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  GET_CUSTOMER: 'GET_CUSTOMER',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
  SET_CUSTOMER: 'SET_CUSTOMER',
  CLEAR_CUSTOMER: 'CLEAR_CUSTOMER',
  SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
  UPDATE_BILLING_ADDRESS: 'UPDATE_BILLING_ADDRESS',
  SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
  UPDATE_SHIPPING_ADDRESS: 'UPDATE_SHIPPING_ADDRESS'
}
