let BASE_URL = QC_BASE_URI

export default {
    BASE_URL: BASE_URL,
    EMPLOYER_URL: BASE_URL + 'account/customer',
    CREATE_EMPLOYER: 'CREATE_EMPLOYER',
    GET_EMPLOYER: 'GET_EMPLOYER',
    UPDATE_EMPLOYER: 'UPDATE_EMPLOYER',
    DELETE_EMPLOYER: 'DELETE_EMPLOYER',
    SET_EMPLOYER: 'SET_EMPLOYER',
    SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
    UPDATE_BILLING_ADDRESS: 'UPDATE_BILLING_ADDRESS',
    SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
    UPDATE_SHIPPING_ADDRESS: 'UPDATE_SHIPPING_ADDRESS'
}