export default {
    CUSTOMER_ID: 'customerId',
    USER_NAME: 'userName',
    DISPLAY_NAME: 'customerDisplayName',
    PREFERRED_NAME: 'preferredName',
    FIRST_NAME: 'firstName',
    MIDDLE_NAME: 'middleName',
	LAST_NAME: 'lastName',
	INITIAL: 'initial',
	TITLE: 'title',
	SALUTATION: 'title',
	SUFFIX: 'suffix',
	GENDER: 'gender',
	MARITAL: 'marital',
	DOB_YEAR: 'dobYear',
	DOB_MONTH: 'dobMonth',
	DOB_DAY: 'dobDay',
	DOB: 'dob',
	SIN: 'sin',
	COMPANY_NAME: 'companyName',
	EMAIL: 'email',
	MOBILE: 'mobile',
	TELEPHONE: 'telephone',
	PASSWORD: 'password',
	CONFIRM: 'confirm'
}